name: fvmhack_backend

on:
  push:
    branches: [master]

jobs:
  Deploy:
    runs-on: [self-hosted,production]
    steps:
      - uses: actions/checkout@master
      - name: down docker
        run: docker-compose down
      - name: clear unused image
        run: yes | docker system prune -a
      - name: Run Docker Compose
        run: docker-compose up --build --force-recreate -d
