name: fvmhack_backend

on:
  push:
    branches: [master]

jobs:
  Deploy:
    runs-on: [self-hosted,production]
    steps:
      - uses: actions/checkout@master
      - name: install
        run: npm install 
      - name: build
        run: npm run build
      - name: start
        run: pm2 start npm -- start
